### ISSUE TITLE
git submodule update failed

### ISSUE THREAD

**Issue by cymqqqq** [RGB-Tools/rgb-lightning-sample#9]
Hi there, I git cloned this repo and executed the git submodule update command, the errors come out:
fatal: Fetched in submodule path 'rust-lightning', but it did not contain bfef26e4c83fef1d87fa020ca21b5406b2e7a129. Direct fetching of that commit failed.
Is it a bug?

**Comment by nicbus** [comment]
The commit has now been made available.

Please note that this project is being archived in favor of `rgb-lightning-node`
